# Generated by Django 5.2.9 on 2026-03-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_hospitaldoctorfeedback_hospitaldoctortimeslotgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedDepressionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField()),
                ('age', models.FloatField()),
                ('education_level', models.IntegerField()),
                ('employment_status', models.IntegerField()),
                ('depression_type', models.IntegerField()),
                ('symptoms', models.IntegerField()),
                ('low_energy', models.IntegerField()),
                ('low_self_esteem', models.IntegerField()),
                ('search_depression_online', models.IntegerField()),
                ('worsening_depression', models.IntegerField()),
                ('overeating_level', models.FloatField()),
                ('eating_frequency', models.IntegerField()),
                ('social_media_hours', models.FloatField()),
                ('social_media_while_eating', models.IntegerField()),
                ('sleep_hours', models.FloatField()),
                ('nervous_level', models.FloatField()),
                ('depression_score', models.FloatField()),
                ('coping_methods', models.IntegerField()),
                ('self_harm', models.IntegerField()),
                ('mental_health_support', models.IntegerField()),
                ('suicide_attempts', models.FloatField()),
                ('is_depressed', models.BooleanField()),
                ('probability', models.FloatField()),
                ('potential_type', models.CharField(max_length=100)),
                ('suggestions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.register')),
            ],
        ),
    ]
